### ISSUE TITLE
heartbeat

### ISSUE THREAD

**Issue by tanneberger** [cryptic-game/python3-lib#11]
**Describe the feature you would like**
An Heartbeat between the main java Server and the python3-lib too determine when one of the too shutsdown. And start functions too reconnect.

**Is your feature request related to a problem? Please describe.**
The Problem is when the server shutdown badly with the TCP connection is still open so the Python3-lib does not get any signal too reconnect.

**Additional context**
Java Server sometimes makes some trouble. Also it is realy more preventiv.

**Comment by felixevers** [comment]
no longer necessary #12
