### ISSUE TITLE
required and optional data

### ISSUE THREAD

**Issue by felixevers** [cryptic-game/python3-lib#2]

**Comment by felixevers** [comment]
Maybe we can pass the required data as parameters instead of a dict. So we can inspect the function parameters via decorator and eliminate the `requires` parameter.

**Comment by tanneberger** [comment]
Yeah could do that but I am not certain it would look ugly because of so many Parameters. I personaly prefer the dict version we can define it once in scheme.py and use it possible for multiple endpoints -> less redundancy

**Comment by tanneberger** [comment]
Should we use the scheme (https://pypi.org/project/scheme/) or go for our own more light weight solution ? @use-to
