### ISSUE TITLE
automatic database-table update

### ISSUE THREAD

**Issue by felixevers** [cryptic-game/python3-lib#4]
**Describe the feature you would like**
When a new version is released, the database structure may have been changed. In this case, the tables should be updated automatically.

**Additional context**
`sqlalchemy` doesnt support this. Look: `sqlalchemy-migrate`

**Comment by tanneberger** [comment]
The Question is what do you wanna do with e.g. a new column with what kind of information do you wanna fill it or just keep it empty ?

**Comment by felixevers** [comment]
This problem is situational.
