### ISSUE TITLE
Prevent error closed by peer

### ISSUE THREAD

**Issue by tanneberger** [cryptic-game/python3-lib#9]
**Describe the bug:**
When the connection get closed by the main java server this error will pop up when the socket tries to recieve further information.

**steps to reproduce**
 skip

**excpected behavior**
Tries to reconnect to server automaticaly dont throw exception.

**screenshoots**
 skip

**desktop**
skip

**solution:**
I will build an exception handler and try periodically to reconnect.

**aditional context**
Its unclear why the java server drops the connection. But the Python3-lib should be cabable of handling such behavior.

**Comment by felixevers** [comment]
Fixed in #12 (v0.3.3)
